### ISSUE TITLE
Crackling audio through DAS on opentpcast

### ISSUE THREAD

**Issue by ghost** [OpenTPCast/Docs#10]
Just upgraded to opentpcast, and for the most part it's working perfectly.
However, I've noticed audio is very crackly..
Put it back onto the old sdcard, and the issue went away.
Has anyone seen this before?

**Comment by NGenesis** [comment]
Make sure that HDMI audio (the device is typically called HTC-VIVE-1) is selected in SteamVR.

Please use the [Community Discord](https://discord.gg/kAbqRGC) for troubleshooting issues rather than opening a bug report.
