### ISSUE TITLE
No Microphone

### ISSUE THREAD

**Issue by brandonmtyler** [OpenTPCast/Docs#11]
First off, I really appreciate the time and effort you all have put into this project.  The instructions are honestly amazing.  You have no obligation to help me really, but I'm wondering if you have any advice...

I followed all the instructions on this page and my TPCast works wonderfully, except my computer and steam still do not recognize the microphone on the Rift. When connecting USB devices, the section USB Audio device never comes up as an option.

The only troubleshooting advice I see is to power cycle everything.  I have done that countless times over the past 2 weeks since I have used the TPCast. Any other suggestions?  Thanks!

**Comment by NGenesis** [comment]
For the Oculus Rift the only devices that will show up in VirtualHere are `Rift` and `Rift Audio`.  Some users have reported that the `Rift Audio` device will only show up after you have used the `Rift` device in VirtualHere.

Please use the community discord at https://discord.gg/kAbqRGC to troubleshoot setup issues.
