### ISSUE TITLE
No Mic

### ISSUE THREAD

**Issue by brandonmtyler** [OpenTPCast/Docs#12]
Not a duplicate. I said Rift in my last post but I meant to say HTC Vive.  

First off, I really appreciate the time and effort you all have put into this project. The instructions are honestly amazing. You have no obligation to help me really, but I'm wondering if you have any advice...

I followed all the instructions on this page and my TPCast works wonderfully, except my computer and steam still do not recognize the microphone on the Vive. When connecting USB devices, the section USB Audio device never comes up as an option.

The only troubleshooting advice I see is to power cycle everything. I have done that countless times over the past 2 weeks since I have used the TPCast. Any other suggestions? Thanks!

**Comment by NGenesis** [comment]
As noted in the [guide](https://github.com/OpenTPCast/Docs/blob/master/guides/UPGRADE.md#connecting-usb-devices), the `USB Audio Device` device will only be listed for older revisions of the HTC Vive.  Newer revisions should use the `Vive Camera` device and ensure that the camera is disabled in SteamVR to enable use of the microphone.

As mentioned in your previously closed issue at https://github.com/OpenTPCast/Docs/issues/11, please use the community discord at https://discord.gg/kAbqRGC to troubleshoot setup issues.
