### ISSUE TITLE
What is the password of the pi user in opentpcast?

### ISSUE THREAD

**Issue by SwimmingTiger** [OpenTPCast/Docs#16]
The image is download from https://github.com/OpenTPCast/Docs/releases/tag/v2.0.1

I want to login from ssh but the password of user `pi` is not the default `raspberry`.

Can you provide your password?

Or I need to change the image and generate a new password.

**Comment by NGenesis** [comment]
https://github.com/OpenTPCast/Docs/blob/master/guides/UPGRADE.md#connecting-to-the-tpcast-over-ssh

> To connect to the TPCast power box to troubleshoot issues or perform further modifications, use the following details:
> 
>     Hostname: tpcast.local
>     Port: 22
>     Username: pi
>     Password: 1qaz2wsx3edc4rfv

**Comment by SwimmingTiger** [comment]
Thank you. I did not find it in the documentation for a long time looking up. My fault. :laughing:
