### ISSUE TITLE
VirtualHere Client suddenly unable to connect to USB hub

### ISSUE THREAD

**Issue by SchmeeboDaBear** [OpenTPCast/Docs#17]
Hi there, I have recently run into an issue using open tpcaast.  I originally set this up about a week and a half ago and it was working great.  I followed all the upgrade steps for moving from tpcast to open tpcast.  However as of today when I attempt to connect my headset to the VIrtualHere Client my Oculus cannot fully connect to the USB hub.  When I look at the system messages, the following message is posted: 

23:59:55 INFO  :Error 'No such host is known. ' getaddrinfo failed for tpcast-2.local.:7575.

I've tried rewriting the latest version of open tpcast on the micro sd card I switched out for the original to no avail.  I've tried deleting and re-downloading the VirtualHere Client to no avail.  I don't know what else to do.

Of note, as of a few days ago Windows 10 updated to a newer version, is it possible that the latest version of open tpcast is not compatible with the new Windows 10 update?

Please let me know whether anyone is experiencing the same problem and whether there are any fixes.  Thank you!

**Comment by NGenesis** [comment]
It seems that the recent Windows 10 update is causing issues with Bonjour.  According to the VirtualHere developer, the fix is to simply uninstall Bonjour from Control Panel > Programs & Features, then run the VirtualHere client which will prompt you to reinstall Bonjour which should resolve the issue.

**Comment by blu31c33** [comment]
i am having the exact same issue.  i have uninstall and reinstalled bonjour using the method you describe above and continue to have the same issue.  what do i need to provide to further troubleshoot?  in my case it connects but than almost immediately goes black on the HMD and the client loses connectivity.  it reconnects but my screen never comes back. i can move the HMD and see the screen move with the hmd.  really strange.  in the past i've rolled back to a previous build.  for some reason windows 10 wont give me that option anymore.

**Comment by obst1** [comment]
> i am having the exact same issue. i have uninstall and reinstalled bonjour using the method you describe above and continue to have the same issue. what do i need to provide to further troubleshoot? in my case it connects but than almost immediately goes black on the HMD and the client loses connectivity. it reconnects but my screen never comes back. 

Ever find a solution?
