### ISSUE TITLE
USB ethernet adapter doesn't work?

### ISSUE THREAD

**Issue by zezba9000** [OpenTPCast/Docs#20]
Hi I'm trying to create a custom image.
Relating to the 'PREPAREIMAGE.md'.

> Disconnect the USB and power cables from the TPCast power box, and connect a USB ethernet adapter into the USB port of the TPCast power box, with an ethernet cable connected to an internet connected router.

What USB to Ethernet adapter are you guys using to get connected to Raspbian?
Have tried two and my router does not seem to find anything.

**Comment by NGenesis** [comment]
I've been using [this](https://www.amazon.co.uk/gp/product/B00AQM8586) USB ethernet adapter, but any 100/1000 rated adapter will work fine, though if you're using a really obscure brand of adapter it might need drivers to work.

**Comment by zezba9000** [comment]
Hmm wonder why mine isn't connecting.

1) I have flashed the micro SD with Win32DiskImage with RaspbianLite.

2) Popped it into the TPCast but it never boots correctly or my USB to Ethernet adapters have issues.

Did I miss some basic step?
Is this the correct port in the image (idk how it wouldn't be): [IMAGE](https://ibb.co/evEZ8T)

**Comment by NGenesis** [comment]
That's the right port.  You could try flashing a microSD with a prebuilt OpenTPCast image and connect via Wi-Fi to see if the USB ethernet adapter is being detected or if it is missing drivers.

**Comment by zezba9000** [comment]
Still doesn't work with official OpenTPCast build. Maybe a driver issue. Will have to do more testing or get one of the ones you're using to confirm.

**Comment by zezba9000** [comment]
Ok so odd work-around. Had to plug the USB to Ethernet adapter into a slower 10/100 switch before plugging into my router. For some reason 10/100/1000 ports may have an issue.

**Also your docs are missing a key step. You need to create a blank "ssh" file in the root directory of your boot partition to enable SSH before you can login and run the OpenTPCast setup scripts.**

**Comment by NGenesis** [comment]
> Also your docs are missing a key step. You need to create a blank "ssh" file in the root directory of your boot partition to enable SSH before you can login and run the OpenTPCast setup scripts.

This is mentioned in step 6 of the image preparation guide at https://github.com/OpenTPCast/Docs/blob/master/guides/PREPAREIMAGE.md#flashing-a-stock-raspbian-stretch-image-to-microsd-card
> 6. In Windows Explorer, navigate to the MicroSD card's boot partition, and create an empty file called ssh.

**Comment by zezba9000** [comment]
Ooops. Missed that.

So have made a custom image. Everything looks fine but it doesn't connect to WiFi.
Have tried to enabled WiFi using "sudo ifconfig eth0 up" but still doesn't connect.

eth1 is the USB to Ethernet so I assume its eth0 for WiFi.

```
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:27:eb:2b:b8:07  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.50.56  netmask 255.255.255.0  broadcast 192.168.50.255
        inet6 fe80::9490:ff10:115b:b969  prefixlen 64  scopeid 0x20<link>
        ether 70:88:6b:83:e3:42  txqueuelen 1000  (Ethernet)
        RX packets 1307  bytes 100183 (97.8 KiB)
        RX errors 0  dropped 20  overruns 0  frame 0
        TX packets 487  bytes 48619 (47.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 11  bytes 1760 (1.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 1760 (1.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
iwconfig
lo        no wireless extensions.

eth1      no wireless extensions.

eth0      no wireless extensions.
```

I've also done the whole 'initwlan' thing as well. Before this. Which works with your image.
