### ISSUE TITLE
Reduced FOV

### ISSUE THREAD

**Issue by dementiacs** [OpenTPCast/Docs#21]
The same thing happens with OpenTPCast as with the official version and is much reported but is there a reason for the image in the HMD to have a  curved pinch at the sides with an odd blue halo at the edge? Doesn't appear when my Oculus is tethered in the normal way.

Can someone look into it and see if a fix is possible?

**Comment by NGenesis** [comment]
Unfortunately this is an issue with the HDMI transmitter that affects all versions of the TPCast and does not have a fix available for the foreseeable future.  There is no simple way that we've found to inspect or modify the firmware on the HDMI transmitter which would make any kind of fix non-trivial for most users to apply if someone was able to figure out a fix.
