### ISSUE TITLE
Black screen after removing headset. Audio still working.

### ISSUE THREAD

**Issue by sebrk** [OpenTPCast/Docs#23]
I'm not entirely sure that this is an OpenTPCast issue as I am still investigating it but so far it seems to be. It is hard to track because the issue is not consistent, i.e. it does not happen every time.

The issue is that when I remove my Rift to do something else often in-game and then return the audio is still working but video has been cut off. The Rift LED is yellow and nothing is transmitted. Is this something that is an acknowledged issue at this point? I will continues posting my findings.

**Comment by DerKorb** [comment]
same for me, incosistent and not sure if its caused by opentpcast.

**Comment by NGenesis** [comment]
This is likely an issue with the HDMI kit which OpenTPCast doesn't change.  You could try covering up the proximity sensor so that the video signal doesn't cut off when removing the HMD.

**Comment by DerKorb** [comment]
I am already doing that (covering the sensor with tape) anyways, so that wont fix it.

**Comment by sebrk** [comment]
After a reinstall of Windows 10 and placing my sender better I've actually gotten rid of the issue. Not sure if that was the actual reason but I'm happy.
