### ISSUE TITLE
VirtualHere doesn't show TPcast

### ISSUE THREAD

**Issue by Raging-Beard** [OpenTPCast/Docs#8]
Doesn't come up at all, any ideas?

Using a 32gb Sandisk Extreme microSD as it's a spare I had, flashed on opentpcast successfully and swapped over, what's going wrong?

**Comment by Raging-Beard** [comment]
It says hub connecting and if I click properties it says;
STATE: Connecting
ADDRESS: tpcast-2.local.:7575 (:7575)

But then it vanishes.

**Comment by apophisnow** [comment]
I'm having the same issue. I don't have a solution yet.

**Comment by apophisnow** [comment]
I was able to get this working by manually specifying the hub by IP address. The problem is most likely firewall or Bonjour.

**Comment by Raging-Beard** [comment]
Hi yeah I did in the end too, thanks.

**Comment by safetychief8** [comment]
I had the exact same problem last night. What's the ip address of the power box?? Is the address, tpcast-2.local.:7575 (:7575) the right login address?
